import type { Metadata } from "next";
import localFont from "next/font/local";
import "@repo/react-ui/styles.css";
import "./globals.css";

/**
 * Geist Sans 폰트 설정
 * 기본 텍스트용 가변 폰트로 다양한 웨이트를 지원합니다.
 */
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});

/**
 * Geist Mono 폰트 설정
 * 코드 표시용 모노스페이스 가변 폰트입니다.
 */
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

/**
 * 페이지 메타데이터 설정
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * 루트 레이아웃 컴포넌트의 속성 인터페이스
 */
interface RootLayoutProps {
  /** 페이지 콘텐츠 */
  children: React.ReactNode;
}

/**
 * 웹 앱의 루트 레이아웃 컴포넌트
 *
 * 모든 페이지에 적용되는 기본 HTML 구조와 폰트 설정을 정의합니다.
 * Geist Sans와 Geist Mono 폰트를 로드하여 CSS 변수로 제공합니다.
 *
 * @param children - 페이지 콘텐츠
 * @returns JSX HTML 문서 구조
 *
 * @example
 * 이 컴포넌트는 Next.js App Router에 의해 자동으로 사용됩니다.
 * 모든 페이지가 이 레이아웃을 상속받습니다.
 */
export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
